export const canonicalGitHubObservation = {
  blocking_review: 'none',
  checks: {
    failed: [],
    passed: ['CI / test', 'lint'],
    pending: [],
    unknown: [],
  },
  draft: false,
  head_revision: '0123456789abcdef0123456789abcdef01234567',
  kind: 'github_pull_request',
  mergeability: 'mergeable',
  review_decision: 'approved',
  review_threads_complete: true,
  state: 'open',
  target: 'github.com/owner/repo#123',
  unresolved_review_threads: 0,
}

export const structuredMonitorLoop = (patch: Record<string, unknown> = {}) => {
  const { active = true, ...monitor } = patch
  return {
    id: 'loop-1',
    slot_key: 'chat-1',
    message: 'Review the pull request when it is ready.',
    idle_secs: 300,
    max_cycles: 0,
    cycle_count: 0,
    active,
    last_fire_ts: 0,
    next_due_ts: 1_800_000_300,
    stopped_reason: '',
    monitor: {
      version: 1,
      config_generation: 1,
      kind: 'github_pull_request',
      target: 'https://github.com/owner/repo/pull/123',
      objective: 'review_ready',
      cadence_secs: 300,
      wake_instructions: 'Address actionable review feedback.',
      budgets: {
        max_runtime_secs: 14_400,
        max_agent_turns: 8,
        max_tokens: 250_000,
        max_provider_errors: 3,
      },
      last_observation: canonicalGitHubObservation,
      last_observation_status: 'pending',
      last_observation_reason_code: 'checks_pending',
      last_observed_at: 1_800_000_000,
      last_fingerprint: 'abc',
      last_wake_fingerprint: '',
      wake_in_flight: false,
      wake_delivery: null,
      wake_count: 2,
      completion_evidence_deadline: 0,
      last_completion_fingerprint: '',
      last_completion_disposition: null,
      last_completed_at: 0,
      token_usage_known: true,
      agent_turns: 2,
      input_tokens: 1200,
      output_tokens: 300,
      probe_count: 5,
      provider_error_count: 1,
      consecutive_provider_errors: 0,
      last_probe_at: 1_800_000_000,
      last_decision: 'no_change',
      last_provider_error: null,
      next_probe_at: 1_800_000_300,
      outcome: null,
      stopped_reason: '',
      stopped_at: 0,
      ...monitor,
    },
  }
}
